#!/bin/sh

set -e
mkdir -p coverage/first

echo "Running fakeredis test suite ..."
istanbul cover test.js --lcovonly
mv 'coverage/lcov.info' 'coverage/first.info'

# node_redis tests subset
echo "Running the compatible subset of the node_redis test suite ..."
istanbul cover redis.test.js --lcovonly

# merging
lcov-result-merger  'coverage/*.info' 'coverage/merged.lcov'
coveralls < 'coverage/merged.lcov'
