#!/bin/sh

# fail fast
set -e

# fakeredis tests
echo ""
echo "Running fakeredis test suite ..."
echo ""
node test

# node_redis tests subset
echo ""
echo "Running the compatible subset of the node_redis test suite ..."
echo ""
node redis.test
